name: ci
# Secrets: BATON_ACCOUNT_ID, BATON_ZOOM_CLIENT_ID, BATON_ZOOM_CLIENT_SECRET
# Variables: CI_{GROUP,ROLE}_ENTITLEMENT, CI_{GROUP,ROLE}_PRINCIPAL
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}
      BATON_ZOOM_CLIENT_ID: ${{ secrets.BATON_ZOOM_CLIENT_ID }}
      BATON_ZOOM_CLIENT_SECRET: ${{ secrets.BATON_ZOOM_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-zoom
        run: go build ./cmd/baton-zoom
      - name: Grant/Revoke group membership
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-zoom
          baton-entitlement: ${{ vars.CI_GROUP_ENTITLEMENT }}
          baton-principal: ${{ vars.CI_GROUP_PRINCIPAL }}
          baton-principal-type: user
          required-secrets: BATON_ACCOUNT_ID,BATON_ZOOM_CLIENT_ID,BATON_ZOOM_CLIENT_SECRET
      - name: Grant/Revoke role membership
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-zoom
          baton-entitlement: ${{ vars.CI_ROLE_ENTITLEMENT }}
          baton-principal: ${{ vars.CI_ROLE_PRINCIPAL }}
          baton-principal-type: user
          required-secrets: BATON_ACCOUNT_ID,BATON_ZOOM_CLIENT_ID,BATON_ZOOM_CLIENT_SECRET
